# Generated by Django 5.1.3 on 2025-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'BannerModel',
                'verbose_name_plural': 'BannerModels',
                'db_table': 'banner',
            },
        ),
    ]
