# Generated by Django 5.1.3 on 2025-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productimagemodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image'),
        ),
    ]
