# Generated by Django 5.1.3 on 2025-06-25 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categorymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
