# Generated by Django 5.1.3 on 2025-06-25 11:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
