# Generated by Django 5.1.3 on 2025-06-25 11:27

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_productmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='table',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
