# Generated by Django 5.1.3 on 2025-06-25 11:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productmodel_table_alter_productmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='table',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Table'),
        ),
    ]
