# Generated by Django 5.1.3 on 2025-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_productmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'OptionsModel',
                'verbose_name_plural': 'OptionsModels',
                'db_table': 'OPtions',
            },
        ),
    ]
