# Generated by Django 5.1.3 on 2025-06-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_optionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.productmodel'),
        ),
    ]
