# Generated by Django 5.1.3 on 2025-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_optionsmodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='optionsmodel',
            name='table',
            field=models.CharField(choices=[('table1', 'Table 1'), ('table2', 'Table 2')], default='table1', max_length=200, verbose_name='Table'),
        ),
    ]
