# Generated by Django 5.1.3 on 2025-06-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_optionsmodel_name_optionsmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=200)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.optionsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
