# Generated by Django 5.1.3 on 2025-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_optionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionvalueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'verbose_name': 'OptionvalueModel',
                'verbose_name_plural': 'OptionvalueModels',
                'db_table': 'optionValue',
            },
        ),
        migrations.RemoveField(
            model_name='optionsmodel',
            name='value',
        ),
        migrations.DeleteModel(
            name='OptionValue',
        ),
        migrations.AddField(
            model_name='optionsmodel',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, to='api.optionvaluemodel', verbose_name='Value'),
        ),
    ]
