# Generated by Django 5.1.3 on 2025-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_optionvaluemodel_remove_optionsmodel_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsmodel',
            name='value',
        ),
        migrations.AddField(
            model_name='optionsmodel',
            name='value',
            field=models.JSONField(default=list),
        ),
    ]
