# Generated by Django 5.1.3 on 2025-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_optionsmodel_value_optionsmodel_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
