# Generated by Django 5.1.3 on 2025-06-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_productmodel_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsmodel',
            name='value',
        ),
        migrations.AddField(
            model_name='optionvaluemodel',
            name='option_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.optionsmodel'),
        ),
    ]
