# Generated by Django 5.1.3 on 2025-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_optionsmodel_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsmodel',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
    ]
