# Generated by Django 5.1.3 on 2025-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_optionsmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsmodel',
            name='value',
            field=models.JSONField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
