# Generated by Django 5.1.3 on 2025-06-26 07:06

import core.apps.api.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_optionsmodel_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='table',
            field=models.TextField(default=core.apps.api.models.product.load_default_description),
        ),
        migrations.AlterField(
            model_name='optionsmodel',
            name='value',
            field=models.JSONField(blank=True, null=True, verbose_name='           Value'),
        ),
    ]
