# Generated by Django 5.1.3 on 2025-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_productmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
