# Generated by Django 5.1.3 on 2025-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_categorymodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
