# Generated by Django 5.1.3 on 2025-06-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_productmodel_is_new_productmodel_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='video_url',
        ),
    ]
