# Generated by Django 5.1.3 on 2025-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_productmodel_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
