# Generated by Django 5.1.3 on 2025-06-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_productmodel_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='video_url',
        ),
    ]
