# Generated by Django 5.1.3 on 2025-06-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_productmodel_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='slug',
        ),
    ]
